build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 80
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8
  TooManyFunctions:
    thresholdInFiles: 25
    thresholdInClasses: 25

style:
  MagicNumber:
    active: false
  ReturnCount:
    active: false

naming:
  active: true
